### ISSUE TITLE
LONG and ULONG Data type width on 64-bit Windows

### ISSUE THREAD

**Issue by Graham--M** [klutzy/rust-windows#10]
Under `ll/types.rs`, `LONG` and `ULONG` are defined as `libc::types::os::arch::c95::c_long` and `libc::types::os::arch::c95::c_ulong` respectively. In `libc` these are defined as 64-bit signed and unsigned integers on X86_64.

However the [Windows Data Type Guide](http://msdn.microsoft.com/en-us/library/windows/desktop/aa383751%28v=vs.85%29.aspx) claims these are 32-bit and the linked [Data Type Ranges Guide](http://msdn.microsoft.com/en-us/library/s3f49ktz.aspx) also claims the `long` type is 32 bits for both 32-bit and 64-bit Visual C++ compilers. Raymond Chen also [wrote that in Win64 only pointers have been expaned to 64-bit](http://blogs.msdn.com/b/oldnewthing/archive/2005/01/31/363790.aspx).

Have the `LONG` and `ULONG` types been tested on 64-bit systems? I haven't access to a 64-bit Windows system to try it.

**Comment by klutzy** [comment]
`c_long` and `c_ulong` are [32-bit on 64-bit Windows](https://github.com/rust-lang/rust/blob/master/src/liblibc/lib.rs#L1464-L1465).
(If you're referencing [rust doc](http://doc.rust-lang.org/libc/types/os/arch/c95/type.c_long.html), it shows 64-bit since the docs are generated on 64-bit linux.)

**Comment by Graham--M** [comment]
Yeah. That's exactly what's happened.
Thanks.
