### ISSUE TITLE
Add Cargo compatibility.

### ISSUE THREAD

**Issue by alexchandel** [klutzy/rust-windows#13]
I'd like to like to depend on this from [screenshot-rs](https://github.com/alexchandel/screenshot-rs) for Windows support. I'd also need `GetDC()` and `SRCCOPY` for taking screenshots.

**Comment by bungcip** [comment]
+1.
Also we need to split rust-windows crate into "nice wrapper" and "*-sys" ones.

**Comment by alexchandel** [comment]
Oh, even better if you can provide a safe API for what I'm trying to do.

What would it be like, this:

```rust
let null = Dc {
    raw: 0,
};
let other_null = GetDC(0);
let hdc = MemoryDc::new(null).unwrap();
let hbmp = hdc.raw.create_compatible_bitmap(1920, 1080);
hdc.select_object(hbmp);
hdc.bit_blt((0, 0), (1920, 1080), other_null, (0, 0), SRCCOPY);
```
?

I'm honestly not sure why `CreateCompatibleDC` takes a NULL but `BitBlt` and `CreateCompatibleBitmap` take a `GetDC(NULL)` in [my attempt](https://github.com/alexchandel/screenshot-rs/blob/master/src/lib.rs#L224), or whether that's necessary at all.

**Comment by alexchandel** [comment]
Ah, also need `GetSystemMetrics`.

**Comment by retep998** [comment]
I already have a separate crate that handles the raw bindings (https://github.com/retep998/winapi-rs) so moving all the raw definitions over there and keeping this project as a nice wrapper would be a good idea.

**Comment by bungcip** [comment]
wow, thats a nice crate you have there @retep998.

**Comment by alexchandel** [comment]
@retep998 Would you be amenable to PRs?

**Comment by retep998** [comment]
@alexchandel I love PRs.

**Comment by alexchandel** [comment]
@retep998 sent one for winapi-rs and one for user32-sys.

**Comment by engstad** [comment]
I think we can close this one now.

**Comment by klutzy** [comment]
Thanks all :D
