### ISSUE TITLE
rust nightly: library target names cannot contain hypens

### ISSUE THREAD

**Issue by majkcramer** [klutzy/rust-windows#23]
up-to-date rust nightly

> cargo build
library target names cannot contain hypens: rust-windows

**Comment by majkcramer** [comment]
error message is simple to resolve for rust-windows. But after then:

C:\Users\blafasel\Downloads\rust-windows-master\rust-windows-master>cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading gdi32-sys v0.1.0
 Downloading log v0.3.1
 Downloading kernel32-sys v0.1.0
 Downloading libc v0.1.6
 Downloading winapi v0.1.17
 Downloading user32-sys v0.1.0
   Compiling kernel32-sys v0.1.0
   Compiling user32-sys v0.1.0
   Compiling gdi32-sys v0.1.0
   Compiling libc v0.1.6
   Compiling winapi v0.1.17
   Compiling log v0.3.1
   Compiling rustwindows v0.0.1 (file:///C:/Users/blafasel/Downloads/rust-windows-m
aster/rust-windows-master)
src\lib.rs:19:14: 19:25 error: expected ident, found `"gdi32-sys"`
src\lib.rs:19 extern crate "gdi32-sys" as gdi32;

**Comment by majkcramer** [comment]
rust 1.0.0-beta: same

**Comment by majkcramer** [comment]
pull-request by gentoo solves BOTH issues.

**Comment by roblabla** [comment]
2796b931f5976488667bbaa53b6f449be328711e is now merged, this can be closed :)
